# Generated by Django 3.0.5 on 2020-04-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')])),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
                ('refShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopplanning', to='backoffice.Shop')),
            ],
            options={
                'ordering': ['refShop', 'day', 'startHour'],
            },
        ),
        migrations.CreateModel(
            name='ProductPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')])),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
                ('refProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productplanning', to='backoffice.Product')),
            ],
            options={
                'ordering': ['refProduct', 'day', 'startHour'],
            },
        ),
    ]
