# Generated by Django 3.0 on 2020-04-26 10:16

from django.db import migrations
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_productplanning_shopplanning'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='html',
            field=django_grapesjs.models.fields.GrapesJsHtmlField(default=''),
            preserve_default=False,
        ),
    ]
