# Generated by Django 3.0 on 2020-04-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_product_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='html',
        ),
    ]
